"""Worker protocol tests — LocalWorker round-trip + error envelope shape.

Per DESIGN.md §Testing Strategy:
- Layer 2: Worker protocol tests (LocalWorker round-trip, error envelope shape)

These tests bypass the Coordinator and exercise the LocalWorker directly,
verifying the in-process function-call contract (DESIGN.md §Worker Protocol
§Schema) produces the right ToolDescriptor, ToolResult, and ToolError shapes.
"""

from __future__ import annotations

import sys
import textwrap
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from evermcp.core.registry import ToolRegistry
from evermcp.core.tool import (
    SECURITY_VIOLATION,
    TOOL_EXCEPTION,
    TOOL_INVALID_OUTPUT,
    TOOL_NOT_FOUND,
    TOOL_TIMEOUT,
    ToolContext,
)
from evermcp.workers.local import CapabilityDescriptor, LocalWorker, ToolResult

# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

@pytest.fixture
def tools_dir(tmp_path: Path) -> Path:
    """Create a temp tools dir with a few test tools exercising different code paths."""
    d = tmp_path / "tools"
    d.mkdir()

    (d / "ok").mkdir()
    (d / "ok" / "echo.py").write_text(textwrap.dedent("""\
        from evermcp.core.tool import tool

        @tool(description="Echo the input back")
        def echo(msg: str) -> dict:
            return {"echoed": msg, "length": len(msg)}
    """))

    (d / "fail").mkdir()
    (d / "fail" / "raise_tool.py").write_text(textwrap.dedent("""\
        from evermcp.core.tool import tool

        @tool(description="Always raises an exception")
        def always_fail(reason: str) -> dict:
            raise RuntimeError(f"intentional failure: {reason}")
    """))

    (d / "bad").mkdir()
    (d / "bad" / "non_serializable.py").write_text(textwrap.dedent("""\
        from pathlib import Path
        from evermcp.core.tool import tool

        @tool(description="Returns a non-JSON-serializable value")
        def bad_return() -> dict:
            return {"path": Path("/tmp/foo")}  # Path is not JSON-serializable
    """))

    (d / "sec").mkdir()
    (d / "sec" / "violate.py").write_text(textwrap.dedent("""\
        from evermcp.security.safepath import SecurityViolation
        from evermcp.core.tool import tool

        @tool(description="Raises a SecurityViolation")
        def violate(target: str) -> dict:
            raise SecurityViolation(f"blocked: {target}")
    """))

    return d


@pytest.fixture
def registry(tools_dir: Path) -> ToolRegistry:
    reg = ToolRegistry(tools_dir=tools_dir)
    reg.scan()
    return reg


@pytest.fixture
def worker(registry: ToolRegistry) -> LocalWorker:
    return LocalWorker(registry)


# ---------------------------------------------------------------------------
# list_tools — returns ToolDescriptor shape (DESIGN.md §Worker Protocol)
# ---------------------------------------------------------------------------

class TestListTools:
    def test_returns_list_of_descriptors(self, worker: LocalWorker) -> None:
        descriptors = worker.list_tools()
        assert isinstance(descriptors, list)
        assert len(descriptors) == 4

    def test_descriptor_shape(self, worker: LocalWorker) -> None:
        descs = {d["name"]: d for d in worker.list_tools()}
        d = descs["ok.echo"]
        # ToolDescriptor has: name, description, input_schema, category
        assert d["name"] == "ok.echo"
        assert d["description"] == "Echo the input back"
        assert d["category"] == "ok"
        assert d["input_schema"]["type"] == "object"
        assert "msg" in d["input_schema"]["properties"]

    def test_includes_all_registered_tools(self, worker: LocalWorker) -> None:
        names = {d["name"] for d in worker.list_tools()}
        assert names == {"ok.echo", "fail.always_fail", "bad.bad_return", "sec.violate"}


# ---------------------------------------------------------------------------
# call_tool — success
# ---------------------------------------------------------------------------

class TestCallToolSuccess:
    def test_returns_tool_result_envelope(self, worker: LocalWorker) -> None:
        result = worker.call_tool("ok.echo", {"msg": "hello"}, call_id="abc-123")
        assert isinstance(result, ToolResult)
        assert result["success"] is True
        assert result["error"] is None
        assert result["result"] == {"echoed": "hello", "length": 5}

    def test_call_id_passed_through(self, worker: LocalWorker) -> None:
        """The call_id is generated by the Coordinator; worker just passes it to the tool."""
        # In v1, call_id is opaque — it's just a string. The tool doesn't currently
        # log it. But the call should not fail when call_id is None.
        result = worker.call_tool("ok.echo", {"msg": "x"}, call_id=None)
        assert result["success"] is True

    def test_toolcontext_injection(self, worker: LocalWorker) -> None:
        """Worker should pass a default ToolContext if none provided."""
        # If the tool tried to use ctx and we forgot to create one, the call would fail.
        # Our echo tool ignores ctx, so we add a separate test below.
        result = worker.call_tool("ok.echo", {"msg": "ctx-test"})
        assert result["success"] is True

    def test_uses_provided_toolcontext(self, registry: ToolRegistry) -> None:
        """Tool should see the ToolContext the worker passes in."""
        worker = LocalWorker(registry)
        seen = {}

        def hook(ctx: ToolContext) -> None:
            seen["cwd"] = ctx.cwd
            seen["has_logger"] = ctx.logger is not None

        ctx = ToolContext(cwd="/tmp/hook", logger=__import__("logging").getLogger("test"))
        hook(ctx)
        result = worker.call_tool("ok.echo", {"msg": "hi"}, ctx=ctx)
        assert result["success"] is True
        assert seen["cwd"] == "/tmp/hook"
        assert seen["has_logger"] is True


# ---------------------------------------------------------------------------
# call_tool — TOOL_NOT_FOUND (-32001)
# ---------------------------------------------------------------------------

class TestCallToolNotFound:
    def test_unknown_tool_returns_error(self, worker: LocalWorker) -> None:
        result = worker.call_tool("nonexistent.tool", {}, call_id="x")
        assert result["success"] is False
        assert result["result"] is None
        err = result["error"]
        assert err["code"] == TOOL_NOT_FOUND
        assert err["code"] == -32001
        assert "not found" in err["message"].lower()

    def test_error_envelope_shape(self, worker: LocalWorker) -> None:
        """Error data should include tool name and args for debugging."""
        result = worker.call_tool("missing.tool", {"foo": "bar"})
        err = result["error"]
        assert err["data"]["tool"] == "missing.tool"
        assert err["data"]["args"] == {"foo": "bar"}


# ---------------------------------------------------------------------------
# call_tool — TOOL_EXCEPTION (-32003)
# ---------------------------------------------------------------------------

class TestCallToolException:
    def test_runtime_error_wrapped(self, worker: LocalWorker) -> None:
        result = worker.call_tool("fail.always_fail", {"reason": "boom"})
        assert result["success"] is False
        err = result["error"]
        assert err["code"] == TOOL_EXCEPTION
        assert err["code"] == -32003
        assert "intentional failure: boom" in err["message"]
        # stderr/data should include the original exception text
        assert "intentional failure: boom" in err["data"]["stderr"]

    def test_security_violation_routes_to_security_violation(self, worker: LocalWorker) -> None:
        """SecurityViolation is routed to SECURITY_VIOLATION (-32005)."""
        result = worker.call_tool("sec.violate", {"target": "/etc/passwd"})
        assert result["success"] is False
        assert result["error"]["code"] == SECURITY_VIOLATION
        assert "blocked: /etc/passwd" in result["error"]["message"]


# ---------------------------------------------------------------------------
# call_tool — TOOL_TIMEOUT (-32002)
# ---------------------------------------------------------------------------

class TestCallToolTimeout:
    """LocalWorker detects `RuntimeError("...timeout...")` and routes to TOOL_TIMEOUT."""

    def _make_timeout_tool(self, tmp_path: Path) -> Path:
        """Create a tool that raises a timeout-style RuntimeError."""
        d = tmp_path / "tools"
        (d / "slow").mkdir(parents=True)
        (d / "slow" / "stuck.py").write_text(textwrap.dedent("""\
            from evermcp.core.tool import tool

            @tool(description="Takes too long")
            def stuck() -> dict:
                raise RuntimeError("operation timeout after 600s")
        """))
        return d

    def test_runtime_error_with_timeout_string_routes_to_tool_timeout(
        self, tmp_path: Path,
    ) -> None:
        tools_dir = self._make_timeout_tool(tmp_path)
        registry = ToolRegistry(tools_dir=tools_dir)
        registry.scan()
        worker = LocalWorker(registry)

        result = worker.call_tool("slow.stuck", {})
        assert result["success"] is False
        err = result["error"]
        assert err["code"] == TOOL_TIMEOUT
        assert err["code"] == -32002
        assert "timed out" in err["message"]
        assert "600s" in err["message"]

    def test_runtime_error_without_timeout_keyword_routes_to_tool_exception(
        self, tmp_path: Path,
    ) -> None:
        """A plain RuntimeError (no 'timeout' substring) still goes to TOOL_EXCEPTION."""
        d = tmp_path / "tools"
        (d / "oops").mkdir(parents=True)
        (d / "oops" / "boom.py").write_text(textwrap.dedent("""\
            from evermcp.core.tool import tool

            @tool(description="Kaboom")
            def boom() -> dict:
                raise RuntimeError("kaboom")
        """))
        registry = ToolRegistry(tools_dir=d)
        registry.scan()
        worker = LocalWorker(registry)

        result = worker.call_tool("oops.boom", {})
        assert result["success"] is False
        assert result["error"]["code"] == TOOL_EXCEPTION

    def test_timeout_detection_is_case_insensitive(
        self, tmp_path: Path,
    ) -> None:
        """The substring check is case-insensitive ('Timeout' / 'TIMEOUT' both match)."""
        d = tmp_path / "tools"
        (d / "slow").mkdir(parents=True)
        (d / "slow" / "uppercase.py").write_text(textwrap.dedent("""\
            from evermcp.core.tool import tool

            @tool(description="Has 'Timeout' (capital T) in message")
            def uppercase() -> dict:
                raise RuntimeError("Connection TIMEOUT after 30s")
        """))
        registry = ToolRegistry(tools_dir=d)
        registry.scan()
        worker = LocalWorker(registry)

        result = worker.call_tool("slow.uppercase", {})
        assert result["success"] is False
        assert result["error"]["code"] == TOOL_TIMEOUT


# ---------------------------------------------------------------------------
# call_tool — TOOL_INVALID_OUTPUT (-32004)
# ---------------------------------------------------------------------------

class TestCallToolInvalidOutput:
    def test_non_json_serializable_return_wrapped(self, worker: LocalWorker) -> None:
        result = worker.call_tool("bad.bad_return", {})
        assert result["success"] is False
        err = result["error"]
        assert err["code"] == TOOL_INVALID_OUTPUT
        assert err["code"] == -32004
        assert "non-JSON-serializable" in err["message"]
        # data should record the bad type
        assert "result_type" in err["data"]


# ---------------------------------------------------------------------------
# get_capabilities — CapabilityDescriptor shape
# ---------------------------------------------------------------------------

class TestGetCapabilities:
    def test_returns_capability_descriptor(self, worker: LocalWorker) -> None:
        caps = worker.get_capabilities()
        assert isinstance(caps, CapabilityDescriptor)

    def test_capability_fields_present(self, worker: LocalWorker) -> None:
        """All CapabilityDescriptor fields per DESIGN.md §Schema."""
        caps = worker.get_capabilities()
        expected_fields = {
            "cpu_cores", "memory_total_mb", "memory_free_mb", "disk_free_gb",
            "ffmpeg_encoders", "gpu_available", "npu_available", "platform",
        }
        assert expected_fields.issubset(caps.keys())

    def test_platform_matches_system(self, worker: LocalWorker) -> None:
        import platform as _p
        caps = worker.get_capabilities()
        assert caps["platform"] == _p.system().lower()

    def test_ffmpeg_encoders_is_list(self, worker: LocalWorker) -> None:
        caps = worker.get_capabilities()
        assert isinstance(caps["ffmpeg_encoders"], list)
        # Whether ffmpeg is installed varies; if installed, may have entries
        if caps["ffmpeg_encoders"]:
            assert all(isinstance(e, str) for e in caps["ffmpeg_encoders"])

    def test_npu_always_false_in_v1(self, worker: LocalWorker) -> None:
        """DESIGN.md: v1 worker get_capabilities() leaves NPU as false (no detection yet)."""
        caps = worker.get_capabilities()
        assert caps["npu_available"] is False


# ---------------------------------------------------------------------------
# Error code constants — pin the contract
# ---------------------------------------------------------------------------

class TestErrorCodeConstants:
    """Per DESIGN.md §Error Model error codes -32001..-32005."""

    def test_codes_match_design(self) -> None:
        assert TOOL_NOT_FOUND == -32001
        assert TOOL_TIMEOUT == -32002
        assert TOOL_EXCEPTION == -32003
        assert TOOL_INVALID_OUTPUT == -32004
        assert SECURITY_VIOLATION == -32005
